### ISSUE TITLE
ImportError: No module named context

### ISSUE THREAD

**Issue by zbmcz** [WangYihang/SourceLeakHacker#5]
```
git clone https://github.com/WangYihang/SourceLeakHacker.git
cd SourceLeakHacker
pip install -r requirments.txt
python SourceLeakHacker.py --url=http://server:port/ --threads=4 --timeout=8 
```

之后出现:

```
Traceback (most recent call last):
  File "SourceLeakHacker.py", line 16, in <module>
    from lib.util import output
  File "/Users/boming/Downloads/SourceLeakHacker-3.0/lib/util/output.py", line 7, in <module>
    from lib.context import context
ImportError: No module named context
```

是我的环境问题吗

**Comment by WangYihang** [comment]
我这边 Python3 测试没问题，你是不是 Python2？（有可能是我没来得及在 2 下测试，如果方便的话先用 3 试试）

**Comment by zbmcz** [comment]
Python3 没问题，多谢，看来我要好好学习一下Python了。

**Comment by WangYihang** [comment]
@zbmcz 好嘞！俺这边 Python2 再测试一下，争取俩版本都能无缝使用。多谢反馈！

**Comment by snow212-cn** [comment]
Python3也无法使用，
`Traceback (most recent call last):
  File "SourceLeakHacker.py", line 11, in <module>
    import prettytable
  File "/home/test/.local/lib/python3.5/site-packages/prettytable/__init__.py", line 3, in <module>
    from .prettytable import (
  File "/home/test/.local/lib/python3.5/site-packages/prettytable/prettytable.py", line 250
    raise Exception(f"Index {index} is invalid, must be an integer or slice")
                                                                           ^
SyntaxError: invalid syntax`

**Comment by xaeroborg** [comment]
I am seeing a similar error 
![image](https://user-images.githubusercontent.com/33274680/147885683-f8d914ef-5aae-4bed-9b1e-f218e9f067d8.png)

**Comment by WangYihang** [comment]
@xaeroborg xaeroborg, Python  2.7 is **not supported**, please use python 3.6+. It works on `Python 3.8.10; Ubuntu 20.04.3 LTS`at least.

**Comment by xaeroborg** [comment]
@WangYihang It works great thanks a ton for the prompt response and Happy New Year
